name: Config Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch latest sing-box release
      id: get_release
      run: |
        api_url="https://api.github.com/repos/SagerNet/sing-box/releases/latest"
        release_data=$(curl -s $api_url)
        deb_url=$(echo $release_data | jq -r '.assets[] | select(.name | endswith("_linux_amd64.deb")) | .browser_download_url')
        echo "Latest release URL: $deb_url"
        echo "DEB_URL=$deb_url" >> $GITHUB_OUTPUT
    - name: Download and install sing-box
      run: |
        set -Eeuo pipefail
        wget -O sing-box.deb "${{ output.DEB_URL }}"
        sudo dpkg -i sing-box.deb

    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml

    - name: Run script
      run: python ../main.py
      working-directory: ./rule/

    - name: Commit and push config.json
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add ./rule/*.json
        git add ./rule/*.srs

        # 检查是否有文件被修改
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Update rules"
          git push
        fi





